// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA96fYCz8svKWN0edemADrmJvL9wFj-dwY',
    appId: '1:1034742796707:web:3959655cf29f55f9988a16',
    messagingSenderId: '1034742796707',
    projectId: 'taskmanagerapp2-c89b5',
    authDomain: 'taskmanagerapp2-c89b5.firebaseapp.com',
    storageBucket: 'taskmanagerapp2-c89b5.firebasestorage.app',
    measurementId: 'G-4CDSM065CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrp05sHkCOkAJWMT7NqqzUhm7Aq4_Q7Yo',
    appId: '1:1034742796707:android:f49e21b74dae9d9c988a16',
    messagingSenderId: '1034742796707',
    projectId: 'taskmanagerapp2-c89b5',
    storageBucket: 'taskmanagerapp2-c89b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1vgdPEk1mpcFlyvwvGuzQF32WmfXxC1E',
    appId: '1:1034742796707:ios:83af3304112bc0c6988a16',
    messagingSenderId: '1034742796707',
    projectId: 'taskmanagerapp2-c89b5',
    storageBucket: 'taskmanagerapp2-c89b5.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1vgdPEk1mpcFlyvwvGuzQF32WmfXxC1E',
    appId: '1:1034742796707:ios:83af3304112bc0c6988a16',
    messagingSenderId: '1034742796707',
    projectId: 'taskmanagerapp2-c89b5',
    storageBucket: 'taskmanagerapp2-c89b5.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA96fYCz8svKWN0edemADrmJvL9wFj-dwY',
    appId: '1:1034742796707:web:dbac516c3af5229c988a16',
    messagingSenderId: '1034742796707',
    projectId: 'taskmanagerapp2-c89b5',
    authDomain: 'taskmanagerapp2-c89b5.firebaseapp.com',
    storageBucket: 'taskmanagerapp2-c89b5.firebasestorage.app',
    measurementId: 'G-F73EVCRVSN',
  );
}
